"""Configuration package"""

from .keywords import (
    BLOCKCHAIN_KEYWORDS,
    PRIVACY_KEYWORDS,
    DATA_GOVERNANCE_KEYWORDS,
    AI_KEYWORDS,
    IOT_KEYWORDS,
    WEIGHTS,
    MIN_SCORE_THRESHOLD,
    HIGH_PRIORITY_THRESHOLD,
    MEDIUM_PRIORITY_THRESHOLD
)

__all__ = [
    'BLOCKCHAIN_KEYWORDS',
    'PRIVACY_KEYWORDS',
    'DATA_GOVERNANCE_KEYWORDS',
    'AI_KEYWORDS',
    'IOT_KEYWORDS',
    'WEIGHTS',
    'MIN_SCORE_THRESHOLD',
    'HIGH_PRIORITY_THRESHOLD',
    'MEDIUM_PRIORITY_THRESHOLD'
]